### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by Rataxes** [iamjpg/Ez-Background-Resize#2] opened 2010-10-11 08:58 UTC
I get double scrollbars in IE7 unless I put overflow:hidden in css

**Comment by iamjpg** [comment] 2010-10-17 17:03
That's interesting.  I can't reproduce this.  It works for me.  Could you post your implementation so I can take a look in IE7?  Thanks.

**Comment by iamjpg** [comment] 2010-10-24 22:41
Closing due to inability to replicate.

**Closed as completed by iamjpg** 2010-10-24 22:41 UTC

**Comment by hayesgm** [comment] 2011-07-25 16:55
I recently witnessed this error on IE8.  I believe my IE8 compatibility fix (see pull requests) solved the issue for my client.
